[package]
name = "dx_audit"
version = "0.0.0"
edition = "2021"

[dependencies]
cargo-lock = "11"
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
packageurl = { version = "0.7", features = ["serde"] }
regex = "1"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-sarif = "0.8"
spdx = "0.13"
thiserror = "2"
toml = { version = "1", default-features = false, features = [
  "parse",
  "serde",
] }
url = "2"
yaml_serde = "0.10"

[lib]
name = "dx_audit"
path = "src/lib.rs"
