load("@rules_dx//typescript/rules:defs.bzl", "typescript_project", "typescript_test")
load("//quality:fixtures.bzl", "real_source_target")

typescript_project(
    name = "app",
    srcs = ["app.ts"],
    declaration = True,
    transpiler = "tsc",
    tsconfig = "tsconfig.json",
    deps = [":util"],
)

typescript_test(
    name = "app_test",
    srcs = ["app_test.ts"],
    config = "jest.config.cjs",
    declaration = True,
    node_modules = "//:node_modules",
    node_options = ["--experimental-vm-modules"],
    transpiler = "tsc",
    tsconfig = "tsconfig.json",
    deps = [":app"],
)

typescript_project(
    name = "test_setup",
    srcs = ["test_setup.ts"],
    declaration = True,
    transpiler = "tsc",
    tsconfig = "tsconfig.json",
    deps = [":util"],
)

typescript_project(
    name = "util",
    srcs = ["util.ts"],
    declaration = True,
    transpiler = "tsc",
    tsconfig = "tsconfig.json",
)

real_source_target(
    name = "corpus_starlark",
    starlark_srcs = ["BUILD.bazel"],
    tags = ["corpus"],
)
