"""Layer-2 full-matrix runner tests (#59, snapshot workflow issue #322).
"""

load("@bazel_skylib//lib:shell.bzl", "shell")
load("//deploy/rules:launcher.bzl", "RUNFILES_BASH_INIT", "rlocation_path")
load("//rust/toolchains:bindings.bzl", "rust_toolchain_toolchains", "rust_toolchain_tools")

def _file_ref(ctx, f):
    """Returns a double-quoted `$(rlocation ...)` ref for one file (issue #317).

    Uses the standard `runfiles.bash` `rlocation` with the rlocation
    single-quoted via `shell.quote`, wrapped in double quotes so paths
    with spaces survive. Replaces manual `$TEST_SRCDIR`-style refs plus
    double-quote escaping.
    """
    return '"$(rlocation ' + shell.quote(rlocation_path(ctx, f)) + ')"'

def _var_ref(var):
    """Returns a double-quoted shell variable ref (for example `$OUT`)."""
    return '"' + var + '"'

def _prefixed_file_ref(ctx, prefix, f):
    """Returns one `prefix + rlocation` word (for example `ws_path=...`).

    Single-quotes the literal prefix via `shell.quote` and concatenates
    the double-quoted `$(rlocation ...)` file ref with no space, so the
    shell sees one word with the literal plus the resolved path.
    """
    return shell.quote(prefix) + _file_ref(ctx, f)

def _single_file(target):
    files = target[DefaultInfo].files.to_list()
    if len(files) != 1:
        fail("runner_matrix_test: target '" + str(target.label) + "' must provide exactly one file")
    return files[0]

def _tool_executable(target):
    # Never index ctx.files positionally: its order is unstable and rule
    # targets (e.g. py_binary launchers) expose several files, which once
    # mapped ruff to pydoclint's entrypoint. The executable is unambiguous.
    exe = target[DefaultInfo].files_to_run.executable
    if exe != None:
        return exe
    return _single_file(target)

def _runner_matrix_test_impl(ctx):
    runner = ctx.executable._runner
    printer = ctx.executable._printer

    # Generated bytes are written at analysis time: deterministic inputs
    # with no new fixture files and no shell-quoting hazards.
    staged = {}  # workspace path -> File staged as its bytes
    for f in ctx.files.srcs:
        staged[f.short_path] = f
    for ws_path in ctx.attr.generated:
        staged[ws_path] = ctx.actions.declare_file(
            ctx.label.name + "_gen/" + ws_path.replace("/", "__").replace("..", "__"),
        )
        ctx.actions.write(output = staged[ws_path], content = ctx.attr.generated[ws_path])
    sibling_staged = {}
    for f in ctx.files.siblings:
        sibling_staged[f.short_path] = f

    tools = {}  # tool name -> binary File
    for i, name in enumerate(ctx.attr.tool_names):
        tools[name] = _tool_executable(ctx.attr.tool_binaries[i])
    if ctx.attr.rustfmt_from_toolchain:
        if "rustfmt" in tools:
            fail("runner_matrix_test: rustfmt_from_toolchain with an explicit rustfmt binary")
        _clippy_driver, rustfmt = rust_toolchain_tools(ctx)
        tools["rustfmt"] = rustfmt

    tool_files = []  # (tool, rel, File)
    for i, tool in enumerate(ctx.attr.toolfile_tools):
        f = _single_file(ctx.attr.toolfile_srcs[i])
        tool_files.append((tool, f.short_path, f))
    configs = []  # (tool, rel)
    for i, tool in enumerate(ctx.attr.config_tools):
        configs.append((tool, _single_file(ctx.attr.config_files[i]).short_path))
    editions = []  # (tool, edition)
    for i, tool in enumerate(ctx.attr.edition_tools):
        editions.append((tool, ctx.attr.edition_values[i]))

    upstream = []  # (tool, File)
    upstream_src_targets = ctx.attr.upstream_srcs
    for i, tool in enumerate(ctx.attr.upstream_tools):
        if i < len(upstream_src_targets):
            upstream.append((tool, _single_file(upstream_src_targets[i])))
        elif tool not in ctx.attr.upstream_generated:
            fail("runner_matrix_test: upstream tool '" + tool + "' has neither upstream_srcs nor upstream_generated bytes")
    for tool, content in ctx.attr.upstream_generated.items():
        # Recorded upstream diagnostics (e.g. delegated Clippy/rustc bytes
        # copied from the parser unit samples): deterministic exec-path
        # inputs with no new fixture files.
        if tool in [t for (t, _f) in upstream]:
            fail("runner_matrix_test: duplicate upstream diagnostics for tool '" + tool + "'")
        diagnostics = ctx.actions.declare_file(ctx.label.name + "_gen/upstream/" + tool + ".diagnostics")
        ctx.actions.write(output = diagnostics, content = content)
        upstream.append((tool, diagnostics))

    expected = ctx.actions.declare_file(ctx.label.name + "_expected.txt")
    ctx.actions.write(output = expected, content = ctx.attr.expected)

    lines = [
        "#!/bin/bash",
        "# Generated by runner_matrix_test. Do not edit.",
        "set -euo pipefail",
        RUNFILES_BASH_INIT,
        "WORK=\"$TEST_TMPDIR/matrix_work\"",
        "mkdir -p \"$WORK/scratch\"",
        # Venv/Node tool launchers (pydoclint, flake8, pylint, eslint,
        # prettier) resolve their runtimes through RUNFILES_DIR; pin it to
        # this test's runfiles root instead of inheriting ambient test env.
        "export RUNFILES_DIR=" + _var_ref("$TEST_SRCDIR"),
        "OUT=\"$WORK/out.pb\"",
        "ACTUAL=\"$WORK/actual.txt\"",
        "fail() { echo \"matrix FAIL: $1\" >&2; exit 1; }",
        # Every referenced file must exist: a missing runfile is a harness
        # bug, never a silent empty input.
        "check_file() { [[ -f \"$1\" ]] || fail \"missing runfile $1\"; }",
    ]
    check_files = []
    producer = str(ctx.label)
    if producer.startswith("@@//"):  # buildifier: disable=canonical-repository
        # Canonical Bzlmod label: pin the human-readable main-repo form.
        producer = "//" + producer[len("@@//"):]  # buildifier: disable=canonical-repository
    run = [_file_ref(ctx, runner)]
    run.append(shell.quote("--producer"))
    run.append(shell.quote(producer))
    run.append(shell.quote("--capability"))
    run.append(shell.quote(ctx.attr.capability))
    run.append(shell.quote("--output"))
    run.append(_var_ref("$OUT"))
    for stage in ctx.attr.stages:
        run.append(shell.quote("--stage"))
        run.append(shell.quote(stage))
    for ws_path, f in staged.items():
        check_files.append(f)
        run.append(shell.quote("--source"))
        run.append(_prefixed_file_ref(ctx, ws_path + "=", f))
    for ws_path, f in sibling_staged.items():
        check_files.append(f)
        run.append(shell.quote("--sibling"))
        run.append(_prefixed_file_ref(ctx, ws_path + "=", f))
    run.append(shell.quote("--real"))
    run.append(shell.quote("--scratch-parent"))
    run.append(_var_ref("$WORK/scratch"))
    for tool, binary in tools.items():
        check_files.append(binary)
        run.append(shell.quote("--tool-binary"))
        run.append(_prefixed_file_ref(ctx, tool + "=", binary))
    for tool, rel in configs:
        run.append(shell.quote("--tool-config"))
        run.append(shell.quote(tool + "=" + rel))
    for tool, edition in editions:
        run.append(shell.quote("--tool-edition"))
        run.append(shell.quote(tool + "=" + edition))
    for tool, rel, f in tool_files:
        check_files.append(f)
        run.append(shell.quote("--tool-file"))
        run.append(_prefixed_file_ref(ctx, tool + "=" + rel + "=", f))

    # Launcher env mirrors real_aspects.bzl: the Python venv stubs locate
    # their interpreter through the runfiles forest, so each staged
    # launcher gets RUNFILES_DIR pointing at this test's runfiles root
    # (the analogue of the aspect's `<runner>.runfiles`); the Node
    # wrappers likewise need JS_BINARY__NO_CD_BINDIR=1. Duplicates resolve
    # last-wins in the runner's cleared env, so explicit case tool_env
    # entries come after the mirrors and win.
    for launcher in ["pydoclint", "flake8", "pylint"]:
        if launcher in tools:
            run.append(shell.quote("--tool-env"))
            run.append(shell.quote(launcher + "=RUNFILES_DIR=") + _var_ref("$TEST_SRCDIR"))
    for launcher in ["eslint", "prettier"]:
        if launcher in tools:
            run.append(shell.quote("--tool-env"))
            run.append(shell.quote(launcher + "=JS_BINARY__NO_CD_BINDIR=1"))
    for env in ctx.attr.tool_env:
        run.append(shell.quote("--tool-env"))
        run.append(shell.quote(env))
    for tool, f in upstream:
        check_files.append(f)
        run.append(shell.quote("--upstream-diagnostics"))
        run.append(_prefixed_file_ref(ctx, tool + "=", f))
    for f in check_files:
        lines.append("check_file " + _file_ref(ctx, f))
    lines.append(" ".join(run) + ' || fail "runner failed"')
    lines.append(
        _file_ref(ctx, printer) +
        " " + _var_ref("$OUT") +
        " > " + _var_ref("$ACTUAL") + ' || fail "printer failed"',
    )

    # Schema validation (issue #322): the decoded print_result shape fails
    # first, so tool-message churn surfaces as a contract error, not a silent
    # byte drift. Checks required headers plus stage/initial/terminal/
    # replacement count consistency via python3 stdlib only.
    lines.append(
        "python3 - " + _var_ref("$ACTUAL") + " <<'PYEOF' || fail \"print_result schema invalid\"\n" +
        "import sys\n" +
        "text = open(sys.argv[1]).read()\n" +
        "lines = text.splitlines()\n" +
        "assert lines, \"empty print_result\"\n" +
        "assert lines[0].startswith(\"producer //\"), \"first line must be producer: \" + lines[0][:80]\n" +
        "assert lines[1] in (\"capability LINT\", \"capability FORMAT\", \"capability TYPECHECK\"), \"bad capability: \" + lines[1]\n" +
        "stages = int([l for l in lines if l.startswith(\"stages \")][0].split()[1])\n" +
        "assert len([l for l in lines if l.startswith(\"stage \")]) == stages, \"stage count mismatch\"\n" +
        "assert any(l.startswith(\"completed_rounds \") for l in lines), \"missing completed_rounds\"\n" +
        "assert any(l == \"convergence STABLE\" for l in lines), \"convergence must stay STABLE\"\n" +
        "PYEOF",
    )
    lines.append(
        # Inline schema check (continued): count initial/terminal/replacement
        # rows against their headers. Kept as a second python block so the
        # generated script stays readable and each failure names its header.
        "python3 - " + _var_ref("$ACTUAL") + " <<'PYEOF' || fail \"print_result counts inconsistent\"\n" +
        "import sys\n" +
        "lines = open(sys.argv[1]).read().splitlines()\n" +
        "def header_count(prefix):\n" +
        "    for l in lines:\n" +
        "        parts = l.split()\n" +
        "        if len(parts) == 2 and parts[0] == prefix:\n" +
        "            return int(parts[1])\n" +
        "    raise AssertionError(\"missing header \" + prefix)\n" +
        "initial = header_count(\"initial\")\n" +
        "terminal = header_count(\"terminal\")\n" +
        "replacements = header_count(\"replacements\")\n" +
        "assert sum(1 for l in lines if l.startswith(\"initial \") and len(l.split()) > 2) == initial, \"initial rows vs header\"\n" +
        "assert sum(1 for l in lines if l.startswith(\"terminal \") and len(l.split()) > 2) == terminal, \"terminal rows vs header\"\n" +
        "assert sum(1 for l in lines if l.startswith(\"replacement \")) == replacements, \"replacement rows vs header\"\n" +
        "assert open(sys.argv[1]).read().endswith(\"\\n\"), \"print_result must end with newline\"\n" +
        "PYEOF",
    )
    lines.append(
        # Snapshot assert with UPDATE_EXPECT refresh (issue #322): byte drift
        # fails with a unified diff; UPDATE_EXPECT=1 stages the fresh actual
        # plus the replacement `expected` block for runner_matrix_cases.bzl.
        "if [[ \"${UPDATE_EXPECT:-0}\" == \"1\" ]]; then\n" +
        "  out_dir=\"${TEST_UNDECLARED_OUTPUTS_DIR:-${TMPDIR:-/tmp}}\"\n" +
        "  mkdir -p \"$out_dir\"\n" +
        "  cp " + _var_ref("$ACTUAL") + " \"$out_dir/" + ctx.label.name + ".expected.update\"\n" +
        "  echo \"snapshot UPDATE_EXPECT: staged fresh actual at $out_dir/" + ctx.label.name + ".expected.update\"\n" +
        "  echo \"paste the block below into runner_matrix_cases.bzl expected for " + ctx.label.name + ":\"\n" +
        "  echo '\"\"\"'\n" +
        "  cat " + _var_ref("$ACTUAL") + "\n" +
        "  echo '\"\"\"'\n" +
        "  echo " + shell.quote("matrix PASS (updated): " + ctx.label.name) + "\n" +
        "  exit 0\n" +
        "fi",
    )
    lines.append(
        "diff -u " + _file_ref(ctx, expected) +
        " " + _var_ref("$ACTUAL") +
        ' || { echo "--- actual print_result:"; cat "$ACTUAL"; echo "re-run with UPDATE_EXPECT=1 to stage the fresh golden (bazel test --test_env=UPDATE_EXPECT), then review before pinning."; fail "golden snapshot mismatch (see diff above)"; }',
    )
    lines.append("echo " + shell.quote("matrix PASS: " + ctx.label.name))

    script = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = script, content = "\n".join(lines) + "\n", is_executable = True)

    runfiles = ctx.runfiles(
        files = (
            [runner, printer, expected] +
            list(staged.values()) +
            list(sibling_staged.values()) +
            list(tools.values()) +
            [f for (_tool, _rel, f) in tool_files] +
            [f for f in ctx.files.config_files] +
            [f for (_tool, f) in upstream]
        ),
    )
    runfiles = runfiles.merge(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    for target in (
        ctx.attr.srcs +
        ctx.attr.siblings +
        ctx.attr.tool_binaries +
        ctx.attr.toolfile_srcs +
        ctx.attr.config_files +
        ctx.attr.upstream_srcs +
        [ctx.attr._runner, ctx.attr._printer]
    ):
        if DefaultInfo in target:
            runfiles = runfiles.merge(target[DefaultInfo].default_runfiles)
    return [DefaultInfo(executable = script, runfiles = runfiles)]

_runner_matrix_test = rule(
    implementation = _runner_matrix_test_impl,
    test = True,
    toolchains = rust_toolchain_toolchains(),
    attrs = {
        "srcs": attr.label_list(
            allow_files = True,
            doc = "Provider-less source files; workspace path is each file's short_path.",
        ),
        "generated": attr.string_dict(
            doc = "Workspace path to bytes written at analysis time (dirty inputs, recorded upstream diagnostics).",
        ),
        "siblings": attr.label_list(
            allow_files = True,
            doc = "Markdown link-resolution siblings; workspace path is each file's short_path.",
        ),
        "capability": attr.string(
            mandatory = True,
            values = ["lint", "format", "typecheck"],
        ),
        "stages": attr.string_list(
            mandatory = True,
            doc = "Runner --stage specs TOOL;classes;paths.",
        ),
        "tool_names": attr.string_list(
            doc = "Parallel to tool_binaries: tool identity per binary.",
        ),
        "tool_binaries": attr.label_list(
            doc = "Parallel to tool_names: spawned tool binaries (executables keep their runfiles).",
        ),
        "toolfile_tools": attr.string_list(
            doc = "Parallel to toolfile_srcs: owning tool per config-closure file.",
        ),
        "toolfile_srcs": attr.label_list(
            allow_files = True,
            doc = "Parallel to toolfile_tools: native-config closure bytes; mirror rel is short_path.",
        ),
        "config_tools": attr.string_list(
            doc = "Parallel to config_files: tools with a primary native config.",
        ),
        "config_files": attr.label_list(
            allow_files = True,
            doc = "Parallel to config_tools: primary config files; rel is short_path.",
        ),
        "edition_tools": attr.string_list(
            doc = "Parallel to edition_values: tools with a crate edition (rustfmt only).",
        ),
        "edition_values": attr.string_list(
            doc = "Parallel to edition_tools: crate edition per tool, passed via --tool-edition.",
        ),
        "tool_env": attr.string_list(
            doc = "Runner --tool-env entries TOOL=K=V (hermetic launcher env).",
        ),
        "upstream_tools": attr.string_list(
            doc = "Parallel to upstream_srcs: delegated tools fed recorded diagnostics.",
        ),
        "upstream_srcs": attr.label_list(
            allow_files = True,
            doc = "Parallel to upstream_tools: recorded upstream diagnostics bytes.",
        ),
        "upstream_generated": attr.string_dict(
            doc = "Tool to recorded upstream diagnostics bytes written at analysis time.",
        ),
        "expected": attr.string(
            mandatory = True,
            doc = "Golden print_result text the decoded result must equal byte-for-byte.",
        ),
        "rustfmt_from_toolchain": attr.bool(
            default = False,
            doc = "Resolve the rustfmt tool binary from the pinned toolchain (never ambient).",
        ),
        "_runner": attr.label(
            default = "//quality/runner:quality_runner",
            executable = True,
            cfg = "target",
        ),
        "_printer": attr.label(
            default = "//quality/result:print_result",
            executable = True,
            cfg = "target",
        ),
        "_runfiles_lib": attr.label(
            default = "@rules_shell//shell/runfiles",
            doc = "Standard runfiles library for `rlocation` (issue #317).",
        ),
    },
)

def runner_matrix_suite(name, cases):
    """Instantiates one `_runner_matrix_test` per matrix case plus a suite.

    Each case is a struct of the rule attrs above plus `name`. All case
    data lives here in `.bzl`; BUILD files only pass the suite name."""
    tests = []
    for case in cases:
        _runner_matrix_test(
            name = case["name"],
            srcs = case.get("srcs", []),
            generated = case.get("generated", {}),
            siblings = case.get("siblings", []),
            capability = case["capability"],
            stages = case["stages"],
            tool_names = case.get("tool_names", []),
            tool_binaries = case.get("tool_binaries", []),
            rustfmt_from_toolchain = case.get("rustfmt_from_toolchain", False),
            toolfile_tools = case.get("toolfile_tools", []),
            toolfile_srcs = case.get("toolfile_srcs", []),
            config_tools = case.get("config_tools", []),
            config_files = case.get("config_files", []),
            edition_tools = case.get("edition_tools", []),
            edition_values = case.get("edition_values", []),
            tool_env = case.get("tool_env", []),
            upstream_tools = case.get("upstream_tools", []),
            upstream_srcs = case.get("upstream_srcs", []),
            upstream_generated = case.get("upstream_generated", {}),
            expected = case["expected"],
            tags = ["no-coverage"],
        )
        tests.append(":" + case["name"])
    native.test_suite(name = name, tests = tests)
