"""Layer-2 full-matrix runner tests (#59).

Runs the real `//quality/runner:quality_runner` binary with `--real`
over provider-less data (source files referenced directly, so they carry
only `DefaultInfo`, plus analysis-time-written generated bytes) and diffs
the decoded result against an inline golden. No `QualitySourcesInfo`
anywhere, so `quality/real_aspects.bzl` yields no actions for these
inputs under any scope: dirty matrix inputs never surface in
`dx lint/format/typecheck --check //...`.

Tool wiring mirrors `real_aspects.bzl`: single-file binaries via
`--tool-binary`, native-config closures via `--tool-config`/`--tool-file`
(mirror-relative paths are the files' `short_path`s), crate editions via
`--tool-edition` (rustfmt only: the aspect passes the `CrateInfo`
edition, falling back to `RUST_EDITION`; matrix cases are provider-less
so they declare the edition explicitly), hermetic launcher
env via `--tool-env`, and delegated Clippy/rustc via
`--upstream-diagnostics` over recorded upstream bytes. Runfiles resolve
as `$TEST_SRCDIR/$TEST_WORKSPACE/<short_path>` for main-repo files and
`$TEST_SRCDIR/<repo>/<path>` for external files (same convention as
`libs/starlark/defs.bzl` plus the `../` strip). rustfmt resolves from the
pinned toolchain via `rustfmt_from_toolchain`, never from ambient host
tools; the venv launchers (pydoclint, flake8, pylint) and Node wrappers
(eslint, prettier) ride as tool binaries with their runfiles merged and
resolve their runtimes through the test `RUNFILES_DIR`, exactly as the
`real_aspects.bzl` forests provide under `dx`.
"""

load("//rust/toolchains:bindings.bzl", "rust_toolchain_toolchains", "rust_toolchain_tools")

def _runfile_ref(f):
    sp = f.short_path
    if sp.startswith("../"):
        return "$TEST_SRCDIR/" + sp[3:]
    return "$TEST_SRCDIR/$TEST_WORKSPACE/" + sp

# Script args are (is_var, text) part lists rendered inside double quotes:
# literal parts are escaped, `$TEST_SRCDIR`-style refs expand. Single-quoting
# is never used: it would freeze the runfiles variables (see #59 proof cell).
def _lit(text):
    return (False, text)

def _var(ref):
    return (True, ref)

def _arg(parts):
    out = ['"']
    for is_var, text in parts:
        if is_var:
            out.append(text)
        else:
            out.append(
                text.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`"),
            )
    out.append('"')
    return "".join(out)

def _single_file(target):
    files = target[DefaultInfo].files.to_list()
    if len(files) != 1:
        fail("runner_matrix_test: target '" + str(target.label) + "' must provide exactly one file")
    return files[0]

def _tool_executable(target):
    # Never index ctx.files positionally: its order is unstable and rule
    # targets (e.g. py_binary launchers) expose several files, which once
    # mapped ruff to pydoclint's entrypoint. The executable is unambiguous.
    exe = target[DefaultInfo].files_to_run.executable
    if exe != None:
        return exe
    return _single_file(target)

def _runner_matrix_test_impl(ctx):
    runner = ctx.executable._runner
    printer = ctx.executable._printer

    # Generated bytes are written at analysis time: deterministic inputs
    # with no new fixture files and no shell-quoting hazards.
    staged = {}  # workspace path -> File staged as its bytes
    for f in ctx.files.srcs:
        staged[f.short_path] = f
    for ws_path in ctx.attr.generated:
        staged[ws_path] = ctx.actions.declare_file(
            ctx.label.name + "_gen/" + ws_path.replace("/", "__").replace("..", "__"),
        )
        ctx.actions.write(output = staged[ws_path], content = ctx.attr.generated[ws_path])
    sibling_staged = {}
    for f in ctx.files.siblings:
        sibling_staged[f.short_path] = f

    tools = {}  # tool name -> binary File
    for i, name in enumerate(ctx.attr.tool_names):
        tools[name] = _tool_executable(ctx.attr.tool_binaries[i])
    if ctx.attr.rustfmt_from_toolchain:
        if "rustfmt" in tools:
            fail("runner_matrix_test: rustfmt_from_toolchain with an explicit rustfmt binary")
        _clippy_driver, rustfmt = rust_toolchain_tools(ctx)
        tools["rustfmt"] = rustfmt

    tool_files = []  # (tool, rel, File)
    for i, tool in enumerate(ctx.attr.toolfile_tools):
        f = _single_file(ctx.attr.toolfile_srcs[i])
        tool_files.append((tool, f.short_path, f))
    configs = []  # (tool, rel)
    for i, tool in enumerate(ctx.attr.config_tools):
        configs.append((tool, _single_file(ctx.attr.config_files[i]).short_path))
    editions = []  # (tool, edition)
    for i, tool in enumerate(ctx.attr.edition_tools):
        editions.append((tool, ctx.attr.edition_values[i]))

    upstream = []  # (tool, File)
    upstream_src_targets = ctx.attr.upstream_srcs
    for i, tool in enumerate(ctx.attr.upstream_tools):
        if i < len(upstream_src_targets):
            upstream.append((tool, _single_file(upstream_src_targets[i])))
        elif tool not in ctx.attr.upstream_generated:
            fail("runner_matrix_test: upstream tool '" + tool + "' has neither upstream_srcs nor upstream_generated bytes")
    for tool, content in ctx.attr.upstream_generated.items():
        # Recorded upstream diagnostics (e.g. delegated Clippy/rustc bytes
        # copied from the parser unit samples): deterministic exec-path
        # inputs with no new fixture files.
        if tool in [t for (t, _f) in upstream]:
            fail("runner_matrix_test: duplicate upstream diagnostics for tool '" + tool + "'")
        diagnostics = ctx.actions.declare_file(ctx.label.name + "_gen/upstream/" + tool + ".diagnostics")
        ctx.actions.write(output = diagnostics, content = content)
        upstream.append((tool, diagnostics))

    expected = ctx.actions.declare_file(ctx.label.name + "_expected.txt")
    ctx.actions.write(output = expected, content = ctx.attr.expected)

    lines = [
        "#!/bin/bash",
        "# Generated by runner_matrix_test. Do not edit.",
        "set -euo pipefail",
        "WORK=\"$TEST_TMPDIR/matrix_work\"",
        "mkdir -p \"$WORK/scratch\"",
        # Venv/Node tool launchers (pydoclint, flake8, pylint, eslint,
        # prettier) resolve their runtimes through RUNFILES_DIR; pin it to
        # this test's runfiles root instead of inheriting ambient test env.
        "export RUNFILES_DIR=" + _arg([_var("$TEST_SRCDIR")]),
        "OUT=\"$WORK/out.pb\"",
        "ACTUAL=\"$WORK/actual.txt\"",
        "fail() { echo \"matrix FAIL: $1\" >&2; exit 1; }",
        # Every referenced file must exist: a missing runfile is a harness
        # bug, never a silent empty input.
        "check_file() { [[ -f \"$1\" ]] || fail \"missing runfile $1\"; }",
    ]
    check_refs = []
    producer = str(ctx.label)
    if producer.startswith("@@//"):  # buildifier: disable=canonical-repository
        # Canonical Bzlmod label: pin the human-readable main-repo form.
        producer = "//" + producer[len("@@//"):]  # buildifier: disable=canonical-repository
    run = [_arg([_var(_runfile_ref(runner))])]
    run.append(_arg([_lit("--producer")]))
    run.append(_arg([_lit(producer)]))
    run.append(_arg([_lit("--capability")]))
    run.append(_arg([_lit(ctx.attr.capability)]))
    run.append(_arg([_lit("--output")]))
    run.append(_arg([_var("$OUT")]))
    for stage in ctx.attr.stages:
        run.append(_arg([_lit("--stage")]))
        run.append(_arg([_lit(stage)]))
    for ws_path, f in staged.items():
        ref = _runfile_ref(f)
        check_refs.append(ref)
        run.append(_arg([_lit("--source")]))
        run.append(_arg([_lit(ws_path + "="), _var(ref)]))
    for ws_path, f in sibling_staged.items():
        ref = _runfile_ref(f)
        check_refs.append(ref)
        run.append(_arg([_lit("--sibling")]))
        run.append(_arg([_lit(ws_path + "="), _var(ref)]))
    run.append(_arg([_lit("--real")]))
    run.append(_arg([_lit("--scratch-parent")]))
    run.append(_arg([_var("$WORK/scratch")]))
    for tool, binary in tools.items():
        ref = _runfile_ref(binary)
        check_refs.append(ref)
        run.append(_arg([_lit("--tool-binary")]))
        run.append(_arg([_lit(tool + "="), _var(ref)]))
    for tool, rel in configs:
        run.append(_arg([_lit("--tool-config")]))
        run.append(_arg([_lit(tool + "=" + rel)]))
    for tool, edition in editions:
        run.append(_arg([_lit("--tool-edition")]))
        run.append(_arg([_lit(tool + "=" + edition)]))
    for tool, rel, f in tool_files:
        ref = _runfile_ref(f)
        check_refs.append(ref)
        run.append(_arg([_lit("--tool-file")]))
        run.append(_arg([_lit(tool + "=" + rel + "="), _var(ref)]))

    # Launcher env mirrors real_aspects.bzl: the Python venv stubs locate
    # their interpreter through the runfiles forest, so each staged
    # launcher gets RUNFILES_DIR pointing at this test's runfiles root
    # (the analogue of the aspect's `<runner>.runfiles`); the Node
    # wrappers likewise need JS_BINARY__NO_CD_BINDIR=1. Duplicates resolve
    # last-wins in the runner's cleared env, so explicit case tool_env
    # entries come after the mirrors and win.
    for launcher in ["pydoclint", "flake8", "pylint"]:
        if launcher in tools:
            run.append(_arg([_lit("--tool-env")]))
            run.append(_arg([_lit(launcher + "=RUNFILES_DIR="), _var("$TEST_SRCDIR")]))
    for launcher in ["eslint", "prettier"]:
        if launcher in tools:
            run.append(_arg([_lit("--tool-env")]))
            run.append(_arg([_lit(launcher + "=JS_BINARY__NO_CD_BINDIR=1")]))
    for env in ctx.attr.tool_env:
        run.append(_arg([_lit("--tool-env")]))
        run.append(_arg([_lit(env)]))
    for tool, f in upstream:
        ref = _runfile_ref(f)
        check_refs.append(ref)
        run.append(_arg([_lit("--upstream-diagnostics")]))
        run.append(_arg([_lit(tool + "="), _var(ref)]))
    for ref in check_refs:
        lines.append("check_file " + _arg([_var(ref)]))
    lines.append(" ".join(run) + ' || fail "runner failed"')
    lines.append(
        _arg([_var(_runfile_ref(printer))]) +
        " " + _arg([_var("$OUT")]) +
        " > " + _arg([_var("$ACTUAL")]) + ' || fail "printer failed"',
    )
    lines.append(
        "diff -u " + _arg([_var(_runfile_ref(expected))]) +
        " " + _arg([_var("$ACTUAL")]) +
        ' || { echo "--- actual print_result:"; cat "$ACTUAL"; fail "golden mismatch (see diff above)"; }',
    )
    lines.append('echo "matrix PASS: ' + ctx.label.name + '"')

    script = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = script, content = "\n".join(lines) + "\n", is_executable = True)

    runfiles = ctx.runfiles(
        files = (
            [runner, printer, expected] +
            list(staged.values()) +
            list(sibling_staged.values()) +
            list(tools.values()) +
            [f for (_tool, _rel, f) in tool_files] +
            [f for f in ctx.files.config_files] +
            [f for (_tool, f) in upstream]
        ),
    )
    for target in (
        ctx.attr.srcs +
        ctx.attr.siblings +
        ctx.attr.tool_binaries +
        ctx.attr.toolfile_srcs +
        ctx.attr.config_files +
        ctx.attr.upstream_srcs +
        [ctx.attr._runner, ctx.attr._printer]
    ):
        if DefaultInfo in target:
            runfiles = runfiles.merge(target[DefaultInfo].default_runfiles)
    return [DefaultInfo(executable = script, runfiles = runfiles)]

_runner_matrix_test = rule(
    implementation = _runner_matrix_test_impl,
    test = True,
    toolchains = rust_toolchain_toolchains(),
    attrs = {
        "srcs": attr.label_list(
            allow_files = True,
            doc = "Provider-less source files; workspace path is each file's short_path.",
        ),
        "generated": attr.string_dict(
            doc = "Workspace path to bytes written at analysis time (dirty inputs, recorded upstream diagnostics).",
        ),
        "siblings": attr.label_list(
            allow_files = True,
            doc = "Markdown link-resolution siblings; workspace path is each file's short_path.",
        ),
        "capability": attr.string(
            mandatory = True,
            values = ["lint", "format", "typecheck"],
        ),
        "stages": attr.string_list(
            mandatory = True,
            doc = "Runner --stage specs TOOL;classes;paths.",
        ),
        "tool_names": attr.string_list(
            doc = "Parallel to tool_binaries: tool identity per binary.",
        ),
        "tool_binaries": attr.label_list(
            doc = "Parallel to tool_names: spawned tool binaries (executables keep their runfiles).",
        ),
        "toolfile_tools": attr.string_list(
            doc = "Parallel to toolfile_srcs: owning tool per config-closure file.",
        ),
        "toolfile_srcs": attr.label_list(
            allow_files = True,
            doc = "Parallel to toolfile_tools: native-config closure bytes; mirror rel is short_path.",
        ),
        "config_tools": attr.string_list(
            doc = "Parallel to config_files: tools with a primary native config.",
        ),
        "config_files": attr.label_list(
            allow_files = True,
            doc = "Parallel to config_tools: primary config files; rel is short_path.",
        ),
        "edition_tools": attr.string_list(
            doc = "Parallel to edition_values: tools with a crate edition (rustfmt only).",
        ),
        "edition_values": attr.string_list(
            doc = "Parallel to edition_tools: crate edition per tool, passed via --tool-edition.",
        ),
        "tool_env": attr.string_list(
            doc = "Runner --tool-env entries TOOL=K=V (hermetic launcher env).",
        ),
        "upstream_tools": attr.string_list(
            doc = "Parallel to upstream_srcs: delegated tools fed recorded diagnostics.",
        ),
        "upstream_srcs": attr.label_list(
            allow_files = True,
            doc = "Parallel to upstream_tools: recorded upstream diagnostics bytes.",
        ),
        "upstream_generated": attr.string_dict(
            doc = "Tool to recorded upstream diagnostics bytes written at analysis time.",
        ),
        "expected": attr.string(
            mandatory = True,
            doc = "Golden print_result text the decoded result must equal byte-for-byte.",
        ),
        "rustfmt_from_toolchain": attr.bool(
            default = False,
            doc = "Resolve the rustfmt tool binary from the pinned toolchain (never ambient).",
        ),
        "_runner": attr.label(
            default = "//quality/runner:quality_runner",
            executable = True,
            cfg = "target",
        ),
        "_printer": attr.label(
            default = "//quality/result:print_result",
            executable = True,
            cfg = "target",
        ),
    },
)

def runner_matrix_suite(name, cases):
    """Instantiates one `_runner_matrix_test` per matrix case plus a suite.

    Each case is a struct of the rule attrs above plus `name`. All case
    data lives here in `.bzl`; BUILD files only pass the suite name.

    Args:
      name: suite name; also the prefix scope for the generated tests.
      cases: list of case structs as produced by `runner_matrix_cases`.
    """
    tests = []
    for case in cases:
        _runner_matrix_test(
            name = case["name"],
            srcs = case.get("srcs", []),
            generated = case.get("generated", {}),
            siblings = case.get("siblings", []),
            capability = case["capability"],
            stages = case["stages"],
            tool_names = case.get("tool_names", []),
            tool_binaries = case.get("tool_binaries", []),
            rustfmt_from_toolchain = case.get("rustfmt_from_toolchain", False),
            toolfile_tools = case.get("toolfile_tools", []),
            toolfile_srcs = case.get("toolfile_srcs", []),
            config_tools = case.get("config_tools", []),
            config_files = case.get("config_files", []),
            edition_tools = case.get("edition_tools", []),
            edition_values = case.get("edition_values", []),
            tool_env = case.get("tool_env", []),
            upstream_tools = case.get("upstream_tools", []),
            upstream_srcs = case.get("upstream_srcs", []),
            upstream_generated = case.get("upstream_generated", {}),
            expected = case["expected"],
            tags = ["no-coverage"],
        )
        tests.append(":" + case["name"])
    native.test_suite(name = name, tests = tests)
