#!/usr/bin/env python3
"""Regenerate performance docs from perf/baseline.json (issue #215).

Numbers in docs/performance.md are regenerated, never hand-written: edit
perf/baseline.json via a human-merged PR (no bot commits), then run

  bazel run //perf:regenerate

to rewrite docs/performance.md. CI fails if the checked-in docs are stale
(see .github/workflows/perf.yml `docs-freshness` step).
"""
import argparse
import json
import os
import pathlib


def resolve_root():
    # `bazel run //perf:regenerate` sets BUILD_WORKSPACE_DIRECTORY to the
    # real checkout; direct `python3 perf/regenerate.py` runs from the
    # checkout already. Never derive the output path from runfiles.
    workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if workspace:
        return pathlib.Path(workspace)
    return pathlib.Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--baseline", default=None)
    parser.add_argument("--output", default=None)
    args = parser.parse_args()
    root = resolve_root()
    baseline = pathlib.Path(args.baseline) if args.baseline else root / "perf" / "baseline.json"
    output = pathlib.Path(args.output) if args.output else root / "docs" / "performance.md"
    doc = json.loads(baseline.read_text(encoding="utf-8"))
    calibration = doc.get("calibration", {})
    benchmarks = doc.get("benchmarks", {})
    policy = doc.get("policy", {})

    lines = []
    lines.append("# Performance")
    lines.append("")
    lines.append(
        "<!-- Generated by `bazel run //perf:regenerate` from perf/baseline.json; "
        "do not edit by hand. -->"
    )
    lines.append("")
    lines.append(
        "Standing benchmark tracking with comparison machinery (issue #215). "
        "Benchmark-gated decisions (ADR 0003 action granularity, codegen milestone "
        "benchmarks, quality-testing permutation benchmarks) run here; a bare number "
        "without comparison is trivia, so this page publishes the committed baseline "
        "plus the comparison policy, never hand-written claims."
    )
    lines.append("")
    lines.append("## Baseline")
    lines.append("")
    lines.append(
        f"Calibrated {calibration.get('date', 'unknown')} on {calibration.get('host', 'unknown')} "
        f"({calibration.get('method', 'see baseline')}). "
        f"Reference fixture: `{calibration.get('reference_fixture', 'unknown')}`. "
        f"Bazel {calibration.get('bazel', 'unknown')}, commit `{calibration.get('commit', 'unknown')}`. "
        f"{calibration.get('budgets', '')}"
    )
    lines.append("")
    lines.append("| Benchmark | Median | Budget | Gate | Tolerance + floor | Reference |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for name in sorted(benchmarks):
        spec = benchmarks[name]
        gate = "gate" if spec.get("gate") else "advisory"
        lines.append(
            f"| `{name}` | {float(spec['baseline_ms']):.1f}ms | "
            f"{float(spec['budget_ms']):.0f}ms | {gate} | "
            f"{float(doc.get('tolerance_relative_default', 0.25)):.0%} + "
            f"{float(spec.get('floor_ms', 0)):.0f}ms | {spec.get('reference', '')} |"
        )
    lines.append("")
    lines.append("## Policy")
    lines.append("")
    lines.append(f"Comparison: {policy.get('comparison', '')}")
    lines.append("")
    lines.append(f"Baseline updates: {policy.get('baseline_updates', '')}")
    lines.append("")
    lines.append(f"{policy.get('no_command_surface', '')}")
    lines.append("")
    lines.append("## Open benchmark-gated decisions")
    lines.append("")
    lines.append(
        "- ADR 0003 (action granularity) stays Provisional: this harness exists, "
        "but the package-vs-file-vs-repository alternative measurements are not "
        "recorded yet. Promotion to Accepted requires recorded evidence here."
    )
    lines.append(
        "- Codegen milestone benchmarks (`docs/environments/codegen.md`) and "
        "quality-testing permutation benchmarks (`docs/quality/quality-testing.md`) "
        "are pending scenario additions to this harness, not separate infrastructure."
    )
    lines.append(
        "- Relative comparison stays advisory until months of stable signal, "
        "then promote per-benchmark (strictness ladder)."
    )
    lines.append("")
    lines.append("## Running benchmarks")
    lines.append("")
    lines.append("```sh")
    lines.append("bazel build //cli/cli:dx //perf:bench_all")
    lines.append("bazel run //perf:bench_micro > /tmp/micro.jsonl")
    lines.append("bazel run //perf:bench_scenario_warm > /tmp/scenario.jsonl")
    lines.append("python3 perf/compare.py --baseline perf/baseline.json /tmp/micro.jsonl /tmp/scenario.jsonl")
    lines.append("```")
    lines.append("")
    lines.append(
        "Scenario cold runs (`generate_check_cold`) execute on `main` plus "
        "`workflow_dispatch` only (free-infra budget); microbenchmarks run per-PR. "
        "See `perf/README.md` and `.github/workflows/perf.yml`."
    )
    lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"perf regenerate: wrote {output}")


if __name__ == "__main__":
    main()
