#!/usr/bin/env bash
# Dogfood-freshness battery (split from `.github/workflows/ci.yml`). No behavior change.
set -euo pipefail

bazel build --noshow_progress @dx_tools//:buildifier @dx_tools//:taplo @dx_tools//:vale //quality/evaluator:quality_evaluator
bazel run --noshow_progress //cli/cli:dx -- generate --check //...
bazel run --noshow_progress //tools/ci:corpus_audit
bazel run --noshow_progress //tools/ci:code_ownership
bazel run --noshow_progress //tools/ci:non_dogfed_paths
bazel run --noshow_progress //tools/ci:non_dogfed_qualification
bazel run --noshow_progress //tools/ci:examples_readme
bazel run --noshow_progress //tools/ci:examples_laziness
bazel run --noshow_progress //tools/ci:examples_laziness_query
bazel run --noshow_progress //tools/ci:examples_laziness_aquery
bazel run --noshow_progress //tools/ci:examples_laziness_runtime
bazel run --noshow_progress //tools/ci:quality_cache_aquery
bazel run --noshow_progress //tools/ci:depcheck_contract
bazel run --noshow_progress //tools/ci:audit_update_guards
bazel run --noshow_progress //tools/ci:product_runtime_guards
bazel run --noshow_progress //tools/ci:wrapper_sources
bazel run --noshow_progress //tools/ci:foundation_maps
bazel run --noshow_progress //tools/ci:registry_singularity
bazel run --noshow_progress //tools/ci:backlog_contracts
bazel run --noshow_progress //tools/ci:dx_facade_qualification
bazel run --noshow_progress //tools/ci:ghcr_hygiene
bazel run --noshow_progress //tools/ci:ghcr_publish_guards
bazel run --noshow_progress //tools/ci:widen_update_loop
bazel run --noshow_progress //tools/ci:build_hygiene
bazel run --noshow_progress //tools/ci:source_hygiene
bazel run --noshow_progress //tools/ci:quality_foundations_guards
bazel run --noshow_progress //tools/ci:distribution_closeout_guards
bazel run --noshow_progress //tools/ci:backlog_automation_guards
bazel run --noshow_progress //tools/ci:supported_evidence_gate
bazel run --noshow_progress //tools/ci:promotion_checklist_qualification
bazel run --noshow_progress //tools/ci:sbom_upload_qualification
bazel run --noshow_progress //tools/ci:quality_adapters_parity
bazel run --noshow_progress //tools/ci:env_codegen_qualification
bazel run --noshow_progress //tools/ci:env_plugins_cgo_qualification
bazel run --noshow_progress //tools/ci:docs_pipeline_qualification
bazel run --noshow_progress //tools/ci:consumer_ci_qualification
bazel run --noshow_progress //tools/ci:review_threads_qualification
bazel run --noshow_progress //tools/ci:file_family_qualification
bazel run --noshow_progress //tools/ci:helper_qualification
bazel run --noshow_progress //tools/ci:clap_tokenizer_qualification
bazel run --noshow_progress //tools/ci:hello_smoke_qualification
bazel run --noshow_progress //tools/ci:parser_sample_qualification
bazel run --noshow_progress //tools/ci:rustfmt_edition_qualification
bazel run --noshow_progress //tools/ci:cc_optout_qualification
bazel run --noshow_progress //tools/ci:cli_contract_qualification
bazel run --noshow_progress //tools/ci:musl_qualification
bazel run --noshow_progress //tools/ci:macos_qualification
bazel run --noshow_progress //tools/ci:windows_qualification
bazel run --noshow_progress //tools/ci:ci_matrix_qualification
bazel run --noshow_progress //tools/ci:skip_budget_qualification
bazel run --noshow_progress //tools/ci:runner_rotation_qualification
bazel run --noshow_progress //tools/ci:ghcr_rebuild_rotation_qualification
bazel run --noshow_progress //tools/ci:devcontainer_boot_qualification
bazel run --noshow_progress //tools/ci:closeout_battery_qualification
bazel run --noshow_progress //tools/ci:rust_library_qualification
bazel run --noshow_progress //tools/ci:selective_update_qualification
bazel run --noshow_progress //tools/ci:selective_cargo_qualification
bazel run --noshow_progress //tools/ci:selective_nuget_qualification
bazel run --noshow_progress //tools/ci:selective_maven_qualification
bazel run --noshow_progress //tools/ci:selective_go_qualification
bazel run --noshow_progress //tools/ci:bump_chain_qualification
bazel run --noshow_progress //tools/ci:bump_discovery_qualification
bazel run --noshow_progress //tools/ci:bump_gha_qualification
bazel run --noshow_progress //tools/ci:update_events_qualification
bazel run --noshow_progress //tools/ci:starlark_futures_qualification
bazel run --noshow_progress //tools/ci:cli_execution_gaps_qualification
bazel run --noshow_progress //tools/ci:layer4_loss_qualification
bazel run --noshow_progress //tools/ci:shell_env_qualification
bazel run --noshow_progress //tools/ci:bindgen_qualification
bazel run --noshow_progress //tools/ci:cxx_identity_qualification
bazel run --noshow_progress //tools/ci:exact_target_qualification
bazel run --noshow_progress //tools/ci:cpp_snapshot_qualification
bazel run --noshow_progress //tools/ci:junit_qualification
bazel run --noshow_progress //tools/ci:xunit_qualification
bazel run --noshow_progress //tools/ci:gotest_qualification
bazel run --noshow_progress //tools/ci:googletest_qualification
bazel run --noshow_progress //tools/ci:scalatest_qualification
bazel run --noshow_progress //tools/ci:maven_lock_qualification
bazel run --noshow_progress //tools/ci:paket_qualification
bazel run --noshow_progress //tools/ci:godeps_qualification
bazel run --noshow_progress //tools/ci:cc_hermetic_qualification
bazel run --noshow_progress //tools/ci:jvm_quality_qualification
bazel run --noshow_progress //tools/ci:scala_dotnet_defaults_qualification
bazel run --noshow_progress //tools/ci:native_quality_qualification
bazel run --noshow_progress //tools/ci:structured_defaults_qualification
bazel run --noshow_progress //tools/ci:file_family_defaults_qualification
bazel run --noshow_progress //tools/ci:scalafix_qualification
bazel run --noshow_progress //tools/ci:roslyn_qualification
bazel run --noshow_progress //tools/ci:fsharplint_qualification
bazel run --noshow_progress //tools/ci:stable_stack_qualification
bazel run --noshow_progress //tools/ci:windows_acquisition_qualification
bazel run --noshow_progress //tools/ci:acquisition_rights_qualification
bazel run --noshow_progress //tools/ci:acquisition_rights_qualification
bazel run --noshow_progress //tools/ci:windows_transport_qualification
bazel run --noshow_progress //tools/ci:prebuilt_interop_qualification
bazel run --noshow_progress //tools/ci:linux_corpus_qualification
bazel run --noshow_progress //tools/ci:deployment_floors_qualification
bazel run --noshow_progress //tools/ci:lcov_accounting_qualification
bazel run --noshow_progress //tools/ci:cargo_metadata_qualification
bazel run --noshow_progress //tools/ci:strict_generation_qualification
bazel run --noshow_progress //tools/ci:cross_routes_qualification
bazel run --noshow_progress //tools/ci:remediation_bounds_qualification
bazel run --noshow_progress //tools/ci:layer2_opens_qualification
bazel run --noshow_progress //tools/ci:result_contract_qualification
bazel run --noshow_progress //tools/ci:quality_taxonomy_qualification
bazel run --noshow_progress //tools/ci:python_audit_qualification
bazel run --noshow_progress //tools/ci:strict_preset_qualification
bazel run --noshow_progress //tools/ci:flakiness_qualification
