#!/usr/bin/env bash
# Maven maven_install.json plus fail_if_repin_required qualification harness.
#
# Qualifies the owned gap from closed /: provisional Maven lock via
# rules_jvm_external, closed / owners only.
# - pinned: rules_jvm_external 7.1 in MODULE.bazel (Bazel >=7.0.0; verified
#   against Bazel 9.2.0 on the seed host) recorded in
#   `third_party/jvm/pins.bzl`; single shared lock for the admitted JVM
#   foundations (Java, Kotlin, Scala managed route shares Java's story, no
#   second lock).
# - wiring: `maven.install` with `lock_file =
#   "//third_party/jvm:maven_install.json"` plus `fail_if_repin_required =
#   True`; the GCS Maven Central mirror lists first (this host's egress
#   proxy serves it while repo1.maven.org answers Cloudflare challenges;
#   the pinned lock hashes make the order irrelevant to artifact identity).
#   The lock is generated by `REPIN=1 bazel run @maven//:pin` and never
#   edited by hand; every entry carries its sha256 so the Bazel downloader
#   verifies each artifact.
# - fixtures: fail-closed consumers over the shared `@maven` hub are the
#   JUnit fixtures (`java/tests/fixtures/junit/` plus
#   `kotlin/tests/fixtures/junit/` Jupiter console-launcher pair over the
#   6.1.3 line, JUnit 4.13.2 seeds via Vintage in the hello fixtures).
#   Non-fail-closed (lock without `fail_if_repin_required`, floating
#   coordinates, hand-edited lock) stays rejected.
# - open owned gaps: platform plus consumer plus release evidence, no
#   `Supported` claim. Compatibility is lock wiring only.
#
# Versioned here, run by CI via `bazel run //tools/ci:maven_lock_qualification`,
# following //tools/ci:googletest_qualification.
set -euo pipefail

# Shared workspace + runfiles helpers.
# Bootstrap via tools/sh/bootstrap.sh (issue #654): runfiles forest first, then source tree.
source "${RUNFILES_DIR:-/dev/null}/_main/tools/sh/bootstrap.sh" 2>/dev/null || source "${TEST_SRCDIR:-/dev/null}/_main/tools/sh/bootstrap.sh" 2>/dev/null || source "$0.runfiles/_main/tools/sh/bootstrap.sh" 2>/dev/null || source "${BASH_SOURCE[0]}.runfiles/_main/tools/sh/bootstrap.sh" 2>/dev/null || source "$(git rev-parse --show-toplevel 2>/dev/null)/tools/sh/bootstrap.sh"
dx_bootstrap "tools/sh/lib.sh"

dx_cd_workspace

dx_test_init

pins="third_party/jvm/pins.bzl"
jvm_build="third_party/jvm/BUILD.bazel"
module="MODULE.bazel"
lock="third_party/jvm/maven_install.json"
java_build="java/tests/fixtures/junit/BUILD.bazel"
kotlin_build="kotlin/tests/fixtures/junit/BUILD.bazel"
java_hello="java/tests/fixtures/hello/BUILD.bazel"
kotlin_hello="kotlin/tests/fixtures/hello/BUILD.bazel"
matrix="docs/product/support-matrix.md"
gen_readme="docs/generation/foundation-qualification.md"
build="tools/ci/BUILD.bazel"
ci=".github/workflows/ci.yml"
verify="docs/testing/verification-matrix.md"

# Lock authority plus pins stay present.
if [[ -f "$pins" && -f "$jvm_build" && -f "$lock" && -f "$module" ]]; then
  ok
else
  bad "maven lock authority missing (want $pins plus $jvm_build plus $lock plus $module)"
fi

# Pins record the resolver plus lock label plus fail-closed flag.
if grep -q -F -e 'RULES_JVM_EXTERNAL_VERSION = "7.1"' "$pins" &&
  grep -q -F -e 'MAVEN_LOCK_FILE = "//third_party/jvm:maven_install.json"' "$pins" &&
  grep -q -F -e 'MAVEN_FAIL_IF_REPIN_REQUIRED = True' "$pins" &&
  grep -q -F -e 'MAVEN_REPIN = "REPIN=1 bazel run @maven//:pin"' "$pins"; then
  ok
else
  bad "pins.bzl lost its rules_jvm_external 7.1 plus lock_file plus fail-closed plus repin identities under issue #481"
fi

# Pins record the artifact list plus repos plus consumers plus rejected wiring.
if grep -q -F -e 'org.junit.jupiter:junit-jupiter-api:6.1.3' "$pins" &&
  grep -q -F -e 'junit:junit:4.13.2' "$pins" &&
  grep -q -F -e 'https://maven-central.storage-download.googleapis.com/maven2' "$pins" &&
  grep -q -F -e 'https://repo1.maven.org/maven2' "$pins" &&
  grep -q -F -e '//java/tests/fixtures/junit:hello_jupiter_test' "$pins" &&
  grep -q -F -e '//kotlin/tests/fixtures/junit:hello_jupiter_test' "$pins" &&
  grep -q -F -e 'non-fail-closed rejected' "$pins"; then
  ok
else
  bad "pins.bzl lost its artifact plus repo plus consumer plus rejected wiring under issue #481"
fi

# MODULE pins the 7.1 resolver line.
if grep -q -F -e 'bazel_dep(name = "rules_jvm_external", version = "7.1")' "$module" &&
  grep -q -F -e 'issue #481' "$module"; then
  ok
else
  bad "MODULE.bazel lost its rules_jvm_external 7.1 pin plus #481 record under issue #481"
fi

# MODULE wires lock_file plus fail_if_repin_required with the mirror order.
if grep -q -F -e 'lock_file = "//third_party/jvm:maven_install.json"' "$module" &&
  grep -q -F -e 'fail_if_repin_required = True' "$module" &&
  grep -q -F -e 'https://maven-central.storage-download.googleapis.com/maven2' "$module" &&
  grep -q -F -e 'https://repo1.maven.org/maven2' "$module" &&
  grep -q -F -e 'org.junit.jupiter:junit-jupiter-api:6.1.3' "$module" &&
  grep -q -F -e 'junit:junit:4.13.2' "$module"; then
  ok
else
  bad "MODULE.bazel lost its lock_file plus fail_if_repin_required plus mirror plus artifact wiring under issue #481"
fi

# Lock records the resolved 6.1.3 line plus 4.13.2 seed plus leaves.
if grep -q -F -e '"org.junit.jupiter:junit-jupiter-api"' "$lock" &&
  grep -q -F -e '"version": "6.1.3"' "$lock" &&
  grep -q -F -e '"junit:junit"' "$lock" &&
  grep -q -F -e '"version": "4.13.2"' "$lock" &&
  grep -q -F -e '"org.jspecify:jspecify"' "$lock" &&
  grep -q -F -e '"org.opentest4j:opentest4j"' "$lock" &&
  grep -q -F -e '__INPUT_ARTIFACTS_HASH' "$lock" &&
  grep -q -F -e '__RESOLVED_ARTIFACTS_HASH' "$lock"; then
  ok
else
  bad "maven_install.json lost its resolved 6.1.3 plus 4.13.2 seed plus leaves plus input/resolved hashes under issue #481"
fi

# Every lock entry carries its sha256 so the downloader verifies each artifact.
if python3 - "$lock" <<'PY' >/dev/null 2>&1
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
artifacts = data.get("artifacts", {})
assert artifacts, "no artifacts"
for coord, entry in artifacts.items():
    shas = entry.get("shasums", {})
    assert shas.get("jar"), "missing jar sha for %s" % coord
    assert entry.get("version"), "missing version for %s" % coord
PY
then
  ok
else
  bad "maven_install.json lost per-artifact sha256 coverage (want shasums.jar plus version on every entry) under issue #481"
fi

# Lock package documents generation plus never-hand-edit plus pins export.
if grep -q -F -e 'REPIN=1 bazel run @maven//:pin' "$jvm_build" &&
  grep -q -F -e 'never edited' "$jvm_build" &&
  grep -q -F -e '"pins.bzl"' "$jvm_build" &&
  grep -q -F -e 'maven_lock_qualification' "$jvm_build"; then
  ok
else
  bad "third_party/jvm/BUILD.bazel lost its REPIN plus never-hand-edit plus pins.bzl plus qualification record under issue #481"
fi

# Java fixtures stay fail-closed consumers over the shared @maven hub (Jupiter
# pair explicit; JUnit 4 seed stays on the default runner).
if grep -q -F -e '@maven//:org_junit_jupiter_junit_jupiter_api' "$java_build" &&
  grep -q -F -e '@maven//:org_junit_platform_junit_platform_console' "$java_build" &&
  grep -q -F -e 'test_class' "$java_hello"; then
  ok
else
  bad "java fixtures lost their @maven fail-closed consumer shape under issue #481"
fi

# Kotlin fixtures stay fail-closed consumers over the shared @maven hub
# (Jupiter pair plus explicit JUnit 4 seed dep).
if grep -q -F -e '@maven//:org_junit_jupiter_junit_jupiter_api' "$kotlin_build" &&
  grep -q -F -e '@maven//:org_junit_platform_junit_platform_console' "$kotlin_build" &&
  grep -q -F -e '@maven//:junit_junit' "$kotlin_hello"; then
  ok
else
  bad "kotlin fixtures lost their @maven fail-closed consumer shape under issue #481"
fi

# Non-fail-closed stays rejected: fail flag never off, lock never hand-edited.
if grep -q -F -e 'fail_if_repin_required = True' "$module" &&
  ! grep -q -F -e 'fail_if_repin_required = False' "$module" &&
  grep -q -F -e '__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY' "$lock"; then
  ok
else
  bad "non-fail-closed Maven wiring detected (want fail_if_repin_required True only plus autogenerated lock)"
fi

# Support matrix keeps the qualified Maven lock wording.
if grep -q -F -e 'Maven maven_install.json qualified seed-only under issue #481' "$matrix" &&
  grep -q -F -e 'maven_lock_qualification' "$matrix" &&
  grep -q -F -e '#481' "$matrix"; then
  ok
else
  bad "docs/product/support-matrix.md lost its qualified Maven lock wording under issue #481"
fi

# Generation README pins the qualified lock alongside the other gaps.
if grep -q -F -e 'qualified Maven maven_install.json' "$gen_readme" &&
  grep -q -F -e 'maven_lock_qualification' "$gen_readme" &&
  grep -q -F -e 'issue #481' "$gen_readme"; then
  ok
else
  bad "docs/generation/foundation-qualification.md lost its qualified Maven lock record under issue #481"
fi

# Verification matrix owns the qualified seed-only record under.
if grep -q -F -e 'maven_lock_qualification' "$verify" &&
  grep -q -F -e 'qualified seed-only under #481' "$verify" &&
  grep -q -F -e 'bazel run //tools/ci:maven_lock_qualification' "$verify" &&
  grep -q -F -e '`maven_lock_qualification` 16/16' "$verify"; then
  ok
else
  bad "verification-matrix lost its #481 Maven lock qualified record"
fi

# BUILD owns the harness target plus CI wires it in dogfood-freshness.
if grep -q -F -e 'name = "maven_lock_qualification"' "$build" &&
  grep -q -F -e 'bazel run --noshow_progress //tools/ci:maven_lock_qualification' "$ci"; then
  ok
else
  bad "tools/ci/BUILD.bazel or ci.yml lost the maven_lock_qualification wiring (want target plus dogfood-freshness)"
fi

# Live proof: the fail-closed @maven consumers execute green on the seed host.
if bazel test //java/tests/fixtures/junit:hello_jupiter_test //kotlin/tests/fixtures/junit:hello_jupiter_test //java/tests/fixtures/hello:hello_test //kotlin/tests/fixtures/hello:hello_test --noshow_progress >/dev/null 2>&1; then
  ok
else
  bad "maven live proof failed (want Jupiter plus JUnit 4 seeds green over the fail-closed lock)"
fi

dx_test_summary "maven lock qualification harness"
