load("//astro/rules:defs.bzl", "astro_library")
load("//javascript/rules:defs.bzl", "javascript_library", "javascript_test")
load("//mdx/rules:defs.bzl", "mdx_library")
load("//quality:fixtures.bzl", "real_source_target")
load("//svelte/rules:defs.bzl", "svelte_library")
load("//vue/rules:defs.bzl", "vue_library")

package(default_visibility = ["//:__subpackages__"])

vue_library(
    name = "vue_lib",
    srcs = ["Hello.vue"],
)

svelte_library(
    name = "svelte_lib",
    srcs = ["Hello.svelte"],
)

astro_library(
    name = "astro_lib",
    srcs = ["Hello.astro"],
)

mdx_library(
    name = "mdx_lib",
    srcs = ["Hello.mdx"],
)

javascript_library(
    name = "helper_lib",
    srcs = ["helper.js"],
)

javascript_test(
    name = "hello_test",
    srcs = ["Hello.test.js"],
    data = [
        ":Hello.astro",
        ":Hello.mdx",
        ":Hello.svelte",
        ":Hello.vue",
        ":helper_lib",
    ],
    node_modules = "//:node_modules",
    node_options = ["--experimental-vm-modules"],
)

real_source_target(
    name = "corpus_markdown",
    aspect_hints = ["//quality:corpus_vale_config"],
    markdown_srcs = ["README.md"],
    tags = ["corpus"],
)

real_source_target(
    name = "corpus_starlark",
    starlark_srcs = ["BUILD.bazel"],
    tags = ["corpus"],
)
