// MTP self-registration shim for Bazel, F# (issue #477).
//
// Generated by Microsoft.Testing.Platform.MSBuild
// (GenerateSelfRegisteredExtensions) under `dotnet build`; checked in here
// because rules_dotnet compiles with fsc, not MSBuild. Registers the pinned
// MTP 2.4.1 plus Telemetry extensions over the xUnit v3 4.0.0 runner.

namespace XunitFixture

open System.Runtime.CompilerServices

[<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
[<Extension>]
type SelfRegisteredExtensions() =

    [<Extension>]
    static member AddSelfRegisteredExtensions(builder: Microsoft.Testing.Platform.Builder.ITestApplicationBuilder, args: string[]) =
        global.Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook.AddExtensions(builder, args)
        global.Microsoft.Testing.Extensions.Telemetry.TestingPlatformBuilderHook.AddExtensions(builder, args)
