// xUnit v3 entry-point shim for Bazel, F# (issue #477).
//
// rules_dotnet compiles with fsc, not MSBuild, so the MSBuild-generated
// XunitAutoGeneratedEntryPoint (xunit.v3.msbuildtasks, from
// xunit.v3.core.mtp-v2 4.0.0) is checked in here instead of generated.
// Adapted from `dotnet new xunit3 --language F#` output (xunit.v3 4.0.x).
// F# compile order matters: this entry point must sort after the test
// sources (BUILD lists it last).

module internal Xunit.AutoGenerated.XunitFixture

[<EntryPoint>]
[<global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
let main args =
    if Array.exists (fun arg -> arg = "--server" || arg = "--internal-msbuild-node") args then
        global.Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, System.Action<_, _>(fun b a -> global.XunitFixture.SelfRegisteredExtensions.AddSelfRegisteredExtensions(b, a))).GetAwaiter().GetResult()
    else
        global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
