
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")
load("//quality:fixtures.bzl", "real_source_target")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

kt_jvm_test(
    name = "hello_jupiter_test",
    srcs = ["HelloJupiterTest.kt"],
    args = [
        "execute",
        "--select-class",
        "hello.HelloJupiterTest",
    ],
    main_class = "org.junit.platform.console.ConsoleLauncher",
    test_class = "hello.HelloJupiterTest",
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_console",
        "@maven//:org_junit_platform_junit_platform_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
    ],
    deps = [
        "//kotlin/tests/fixtures/hello:hello_lib",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
    ],
)

real_source_target(
    name = "corpus_starlark",
    testonly = True,
    aspect_hints = ["//:buildifier_config"],
    starlark_srcs = ["BUILD.bazel"],
    tags = ["corpus"],
)
