// MTP self-registration shim for Bazel (issue #477).
//
// Generated by Microsoft.Testing.Platform.MSBuild
// (GenerateSelfRegisteredExtensions) under `dotnet build`; checked in here
// because rules_dotnet compiles with csc, not MSBuild. Registers the pinned
// MTP 2.4.1 plus Telemetry extensions over the xUnit v3 4.0.0 runner.

namespace XunitFixture
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Microsoft.CodeAnalysis.Embedded]
    internal static class SelfRegisteredExtensions
    {
        public static void AddSelfRegisteredExtensions(this global::Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder, string[] args)
        {
            global::Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook.AddExtensions(builder, args);
            global::Microsoft.Testing.Extensions.Telemetry.TestingPlatformBuilderHook.AddExtensions(builder, args);
        }
    }
}

namespace Microsoft.CodeAnalysis
{
    internal sealed partial class EmbeddedAttribute : global::System.Attribute
    {
    }
}
