// xUnit v3 entry-point shim for Bazel.
//
// rules_dotnet compiles with csc, not MSBuild, so the MSBuild-generated
// XunitAutoGeneratedEntryPoint (xunit.v3.msbuildtasks, from
// xunit.v3.core.mtp-v2 4.0.0) is checked in here instead of generated.
// Adapted from `dotnet new xunit3` output (xunit.v3 4.0.x): the test
// assembly stays a plain `csharp_test` executable; direct `dotnet run`
// and MTP `--server` modes both route through the pinned runner.

namespace Xunit.AutoGenerated.XunitFixture
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal class XunitAutoGeneratedEntryPoint
    {
        public static int Main(string[] args)
        {
            if (global::System.Linq.Enumerable.Any(args, arg => arg == "--server" || arg == "--internal-msbuild-node"))
                return global::Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, global::XunitFixture.SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult();
            else
                return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
        }
    }
}
